import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <Script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCIL7VTumEd-y8-pBlw90Gve53z6F_rToM&callback=Function.prototype"></Script> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
